// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkatTnUAOR0Q_XOvWiagEhdz_z3T0ok8k',
    appId: '1:774685835021:web:5b9818786e55b15309fa44',
    messagingSenderId: '774685835021',
    projectId: 'mahloula-37b47',
    authDomain: 'mahloula-37b47.firebaseapp.com',
    storageBucket: 'mahloula-37b47.firebasestorage.app',
    measurementId: 'G-ZFSYRBZQ5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDeswaNtUoh5Pqk-Xc55mWoHOFgSdroM',
    appId: '1:160217474119:android:3ae088594c3feafddefd62',
    messagingSenderId: '160217474119',
    projectId: 'ma7lola-75b28',
    storageBucket: 'ma7lola-75b28.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdsTVFzMyuWRUJVvvh0fWqPs-UxcMgtZ8',
    appId: '1:160217474119:ios:7708f6282e856999defd62',
    messagingSenderId: '160217474119',
    projectId: 'ma7lola-75b28',
    storageBucket: 'ma7lola-75b28.firebasestorage.app',
    iosBundleId: 'com.ma7lola.ma7lolaVendor',
  );
}
